In [1]:
run = "before_selection" # before_selection
labels = "dataset_labelled_tweets"

In [2]:
import pandas as pd
import numpy as np
from functools import reduce

# Merge

In order to feed data into the classifier, we need to normalise the feature vectorlengths

Merging
- before_selection
    - feature vector generated from Play
- dataset_labelled_tweets

This notebook merges the information types, topics and ground truth set, generates dummy data, and then splits.

Outputs:
- `df_int.csv`
- `df_char.csv`

## Helper methods

In [3]:
def clean_dataset_char(df):
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    #df.dropna(inplace=True)
    return df


def clean_dataset_int(df):
    df = df_t.drop(['category','matchedName','eventType','eventID'],axis =1)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    df.replace(np.nan,0)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    df.astype(int)
    df = df.replace(r'\D+', '', regex=True)
    return df[indices_to_keep].astype(np.float64)

def clean_final_dataset(df):
    df = df.drop(['category','eventID','eventType','eventID'],axis =1)
    #df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    #df.replace(np.nan,0)
    #indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    #df = df.replace(r'\D+', '', regex=True)
    return df
    #return df[indices_to_keep].astype(np.int64)

def merge_datasets(df):
    dfs = [dataset_labelled, df]
    df_final = reduce(lambda left,right: pd.merge(left,right,on='tweet_id'), dfs)
    return df_final

## Load the labelled Tweets

In [4]:
dataset_labelled = pd.read_csv("../3-csv/" + labels + ".csv")
dataset_labelled['category'] = dataset_labelled['category'].str.lower()
dataset_labelled

,tweet_id,priority,category,postCategories_x,eventID,eventType
0,1128285482784366592,0.75,location,12,papuaNewguineaEarthquake2020,Unknown
1,1128285482784366592,0.75,factoid,12,papuaNewguineaEarthquake2020,Unknown
2,1128285665186197504,0.25,location,12,papuaNewguineaEarthquake2020,Unknown
3,1128285665186197504,0.25,factoid,12,papuaNewguineaEarthquake2020,Unknown
4,1128285665186197504,0.25,hashtags,12,papuaNewguineaEarthquake2020,Unknown
...,...,...,...,...,...,...
15264,1162006062867918848,0.25,irrelevant,16,typhoonKrosa2020,Unknown
15265,1162006062867918848,0.25,location,16,typhoonKrosa2020,Unknown
15266,1162006062867918848,0.25,multimediashare,16,typhoonKrosa2020,Unknown
15267,1162006062867918848,0.25,hashtags,16,typhoonKrosa2020,Unknown
15268,1162006062867918848,0.25,news,16,typhoonKrosa2020,Unknown

## Load the run file

This is the feature vector generated in `Play Framework`

In [5]:
df = pd.read_csv("../3-csv/" +run + ".csv")
df

,tweet_id,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1.155485e+18,2.0,66.0,15.0,99.0,18.0,42.0,0.0,11.0,11.0,11.0
1,1.155487e+18,1.0,39.0,52.0,257.0,7709.0,2814.0,392.0,0.0,0.0,0.0
2,1.155488e+18,2.0,63.0,17.0,98.0,537.0,1486.0,20.0,0.0,0.0,0.0
3,1.155494e+18,4.0,57.0,63.0,257.0,295.0,2145.0,2.0,10.0,11.0,10.0
4,1.155495e+18,15.0,42.0,40.0,217.0,1682.0,104.0,51.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2944,1.158759e+18,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
2945,1.158759e+18,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
2946,1.158760e+18,5.0,37.0,12.0,57.0,220.0,61.0,3.0,33.0,22.0,26.0
2947,1.158762e+18,9.0,28.0,8.0,70.0,33.0,0.0,4.0,16.0,11.0,13.0
2948,1.158763e+18,3.0,19.0,9.0,68.0,1592.0,523.0,94.0,20.0,11.0,14.0

In [6]:
df_final = merge_datasets(df)
df_final

,tweet_id,priority,category,postCategories_x,eventID,eventType,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1155790457470967808,0.25,location,18,siberianWildfires2020,Unknown,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
1,1155790457470967808,0.25,emergingthreats,18,siberianWildfires2020,Unknown,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
2,1155790457470967808,0.25,multimediashare,18,siberianWildfires2020,Unknown,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
3,1155790457470967808,0.25,originalevent,18,siberianWildfires2020,Unknown,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
4,1155790457470967808,0.25,location,18,siberianWildfires2020,Unknown,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,1158759125603323904,0.25,factoid,16,siberianWildfires2020,Unknown,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
508,1158759125603323904,0.25,news,16,siberianWildfires2020,Unknown,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
509,1158759326091227136,0.25,multimediashare,14,siberianWildfires2020,Unknown,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
510,1158759326091227136,0.25,contextualinformation,14,siberianWildfires2020,Unknown,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
511,1158759326091227136,0.25,irrelevant,14,siberianWildfires2020,Unknown,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0

In [7]:
df_final = clean_final_dataset(df_final)
df_final
#df_new['tweet_id'] = df_final['tweet_id']

,tweet_id,priority,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
1,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
2,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
3,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
4,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,1158759125603323904,0.25,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
508,1158759125603323904,0.25,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
509,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
510,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
511,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0

In [8]:

df_final.to_csv("../3-csv/df_final_trimmed.csv", index=False)

df_final

,tweet_id,priority,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
1,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
2,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
3,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
4,1155790457470967808,0.25,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,1158759125603323904,0.25,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
508,1158759125603323904,0.25,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
509,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
510,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
511,1158759326091227136,0.25,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0

In [9]:
del df_final['priority']

df_final
df_final.to_csv("../3-csv/df_final_cut.csv", index=False)
df_final

,tweet_id,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1155790457470967808,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
1,1155790457470967808,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
2,1155790457470967808,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
3,1155790457470967808,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
4,1155790457470967808,18,7.0,50.0,43.0,230.0,3726.0,1013.0,799.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
507,1158759125603323904,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
508,1158759125603323904,16,3.0,65.0,8.0,57.0,550.0,720.0,7.0,14.0,11.0,12.0
509,1158759326091227136,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
510,1158759326091227136,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0
511,1158759326091227136,14,7.0,47.0,15.0,80.0,106.0,124.0,0.0,22.0,22.0,22.0

### TODO: map eventID -> numeric value

In [10]:
dataset_labelled_char = clean_dataset_char(dataset_labelled)
dataset_labelled_char.head()

,tweet_id,priority,category,postCategories_x,eventID,eventType
0,1128285482784366592,0.75,location,12,papuaNewguineaEarthquake2020,Unknown
1,1128285482784366592,0.75,factoid,12,papuaNewguineaEarthquake2020,Unknown
2,1128285665186197504,0.25,location,12,papuaNewguineaEarthquake2020,Unknown
3,1128285665186197504,0.25,factoid,12,papuaNewguineaEarthquake2020,Unknown
4,1128285665186197504,0.25,hashtags,12,papuaNewguineaEarthquake2020,Unknown

In [11]:
#df_char['matchedName'] = [str(x) for x in df_char['matchedName']]
#df_char['informationType'] = df_char['matchedName'].apply(lambda x: ','.join(map(str, x)))
#df_char['matchedName'] = df_char['matchedName'].str[:-1]
#df.sort_values(by=['label_id'])
#merged_df = pd.merge(before_selection, df_int, left_on = 'tweet_id', right_on = 'tweet_id', how = 'inner')
# Timestamp will need to be reconfigured as index on each load
#df = df.set_index('timestamp')