In [1]:
run = "before_selection" # before_selection
labels = "dataset_labelled_tweets"

In [2]:
import pandas as pd
import numpy as np
from functools import reduce

# Merge

In order to feed data into the classifier, we need to normalise the feature vectorlengths

Merging
- before_selection
    - feature vector generated from Play
- dataset_labelled_tweets

This notebook merges the information types, topics and ground truth set, generates dummy data, and then splits.

Outputs:
- `df_int.csv`
- `df_char.csv`

## Helper methods

In [3]:
def clean_dataset_char(df):
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    #df.dropna(inplace=True)
    return df


def clean_dataset_int(df):
    df = df_t.drop(['category','matchedName','eventType','eventID'],axis =1)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    df.replace(np.nan,0)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    df.astype(int)
    df = df.replace(r'\D+', '', regex=True)
    return df[indices_to_keep].astype(np.float64)

def clean_final_dataset(df):
    df = df.drop(['category','eventID','eventType','eventID'],axis =1)
    #df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    #df.replace(np.nan,0)
    #indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    #df = df.replace(r'\D+', '', regex=True)
    return df
    #return df[indices_to_keep].astype(np.int64)

def merge_datasets(df):
    dfs = [dataset_labelled, df]
    df_final = reduce(lambda left,right: pd.merge(left,right,on='tweet_id'), dfs)
    return df_final

## Load the labelled Tweets

In [4]:
dataset_labelled = pd.read_csv("../3-csv/" + labels + ".csv")
dataset_labelled['category'] = dataset_labelled['category']#.str.lower()
dataset_labelled

,tweet_id,priority,category,postCategories_x,eventID,eventType
0,1128285482784366592,0.75,Location,12,papuaNewguineaEarthquake2020,Unknown
1,1128285482784366592,0.75,Factoid,12,papuaNewguineaEarthquake2020,Unknown
2,1128285665186197504,0.25,Location,12,papuaNewguineaEarthquake2020,Unknown
3,1128285665186197504,0.25,Factoid,12,papuaNewguineaEarthquake2020,Unknown
4,1128285665186197504,0.25,Hashtags,12,papuaNewguineaEarthquake2020,Unknown
...,...,...,...,...,...,...
15264,1162006062867918848,0.25,Irrelevant,16,typhoonKrosa2020,Unknown
15265,1162006062867918848,0.25,Location,16,typhoonKrosa2020,Unknown
15266,1162006062867918848,0.25,MultimediaShare,16,typhoonKrosa2020,Unknown
15267,1162006062867918848,0.25,Hashtags,16,typhoonKrosa2020,Unknown
15268,1162006062867918848,0.25,News,16,typhoonKrosa2020,Unknown

## Load the run file

This is the feature vector generated in `Play Framework`

In [5]:
df = pd.read_csv("../3-csv/" +run + ".csv")
df

,tweet_id,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1.147938e+18,1.0,66.0,75.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
1,1.148275e+18,1.0,66.0,79.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
2,1.148275e+18,1.0,66.0,78.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
3,1.148401e+18,64.0,4.0,18.0,62.0,1608.0,837.0,10.0,0.0,0.0,0.0
4,1.148489e+18,1.0,62.0,77.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1065,1.158879e+18,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1066,1.158884e+18,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1067,1.158887e+18,2.0,63.0,39.0,167.0,1.0,1.0,0.0,0.0,0.0,0.0
1068,1.158888e+18,10.0,42.0,11.0,57.0,92.0,306.0,6.0,14.0,11.0,12.0
1069,1.158888e+18,1.0,54.0,32.0,108.0,85.0,2.0,2.0,0.0,0.0,0.0

In [6]:
df_final = merge_datasets(df)
df_final.to_csv("../3-csv/df_final_trimmed.csv", index=False)


df_final

,tweet_id,priority,category,postCategories_x,eventID,eventType,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1148495760876552192,0.25,Weather,24,hurricaneBarry2020,Unknown,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
1,1148495760876552192,0.25,MultimediaShare,24,hurricaneBarry2020,Unknown,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
2,1148495760876552192,0.25,Irrelevant,24,hurricaneBarry2020,Unknown,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
3,1148629055387963392,0.25,Factoid,17,hurricaneBarry2020,Unknown,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
4,1148629055387963392,0.25,Location,17,hurricaneBarry2020,Unknown,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1158879279884701696,0.25,Irrelevant,11,baltimoreFlashFlood2020,Unknown,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1270,1158879279884701696,0.25,Irrelevant,11,baltimoreFlashFlood2020,Unknown,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1271,1158883650865438720,0.25,Irrelevant,11,baltimoreFlashFlood2020,Unknown,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1272,1158883650865438720,0.25,Irrelevant,11,baltimoreFlashFlood2020,Unknown,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1273,1158883650865438720,0.25,Irrelevant,11,baltimoreFlashFlood2020,Unknown,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0

In [7]:
df_final = clean_final_dataset(df_final)
df_final
#df_new['tweet_id'] = df_final['tweet_id']

,tweet_id,priority,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
1,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
2,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
3,1148629055387963392,0.25,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
4,1148629055387963392,0.25,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1158879279884701696,0.25,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1270,1158879279884701696,0.25,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1271,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1272,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1273,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0

In [8]:

df_final.to_csv("../3-csv/df_final_trimmed.csv", index=False)

df_final

,tweet_id,priority,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
1,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
2,1148495760876552192,0.25,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
3,1148629055387963392,0.25,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
4,1148629055387963392,0.25,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1158879279884701696,0.25,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1270,1158879279884701696,0.25,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1271,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1272,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1273,1158883650865438720,0.25,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0

In [9]:
del df_final['priority']

df_final
df_final.to_csv("../3-csv/df_final_cut.csv", index=False)
df_final

,tweet_id,postCategories_x,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,1148495760876552192,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
1,1148495760876552192,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
2,1148495760876552192,24,13.0,9.0,4.0,32.0,290.0,2199.0,7.0,0.0,0.0,0.0
3,1148629055387963392,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
4,1148629055387963392,17,1.0,65.0,76.0,276.0,51.0,12.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1158879279884701696,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1270,1158879279884701696,11,9.0,25.0,8.0,32.0,28630.0,1383.0,684.0,0.0,0.0,0.0
1271,1158883650865438720,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1272,1158883650865438720,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0
1273,1158883650865438720,11,7.0,53.0,8.0,54.0,158785.0,1266.0,1393.0,0.0,0.0,0.0

### TODO: map eventID -> numeric value

In [10]:
dataset_labelled_char = clean_dataset_char(dataset_labelled)
dataset_labelled_char.head()

,tweet_id,priority,category,postCategories_x,eventID,eventType
0,1128285482784366592,0.75,Location,12,papuaNewguineaEarthquake2020,Unknown
1,1128285482784366592,0.75,Factoid,12,papuaNewguineaEarthquake2020,Unknown
2,1128285665186197504,0.25,Location,12,papuaNewguineaEarthquake2020,Unknown
3,1128285665186197504,0.25,Factoid,12,papuaNewguineaEarthquake2020,Unknown
4,1128285665186197504,0.25,Hashtags,12,papuaNewguineaEarthquake2020,Unknown

In [11]:
#df_char['matchedName'] = [str(x) for x in df_char['matchedName']]
#df_char['informationType'] = df_char['matchedName'].apply(lambda x: ','.join(map(str, x)))
#df_char['matchedName'] = df_char['matchedName'].str[:-1]
#df.sort_values(by=['label_id'])
#merged_df = pd.merge(before_selection, df_int, left_on = 'tweet_id', right_on = 'tweet_id', how = 'inner')
# Timestamp will need to be reconfigured as index on each load
#df = df.set_index('timestamp')