In [1]:
run = "df_int"

In [2]:
import pandas as pd
import seaborn as sns
from igel import Igel
import numpy as np

In [3]:
def clean_dataset_char(df):
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    df.dropna(inplace=True)
    return df


def clean_dataset_int(df):
    df.fillna(0, inplace=True)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    df.replace(np.nan,0)
    df = df.replace(r'\D+', '', regex=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)
    #return df

## Overview

This notebook is an attemp to split (a) dataset(s) into train/score

In [ ]:
train_df = pd.read_csv("df_int.csv")
score_df = pd.read_csv("before_selection.csv")

#score_df = clean_dataset(score_df)
#train_df = clean_dataset(train_df)

train_df['label'] = '0' #train
score_df['label'] = '1' #score

In [9]:
score_df.head()

,Unnamed: 0,tweet_id,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure,label
0,0,1.155485e+18,20,660,150,990,180,420,0,11109999656677246,11109999656677246,11109999656677246,1
1,1,1.155487e+18,10,390,520,2570,77090,28140,3920,0,0,0,1
2,2,1.155488e+18,20,630,170,980,5370,14860,200,0,0,0,1
3,3,1.155494e+18,40,570,630,2570,2950,21450,20,100,11109999656677246,10529999732971191,1
4,4,1.155495e+18,150,420,400,2170,16820,1040,510,0,0,0,1

In [4]:
train_df.head()

     Unnamed: 0      tweet_id  priority  postCategories_x label
0             0  2.115660e+17      0.75              19.0     0
1             1  2.116544e+17      0.50              15.0     0
2             2  2.116813e+17      0.25              15.0     0
3             3  2.116856e+17      0.25              16.0     0
4             4  2.118770e+17      0.25               7.0     0
..          ...           ...       ...               ...   ...
938         938  3.963360e+17      0.25              15.0     0
939         939  3.963361e+17      0.25              15.0     0
940         940  3.963362e+17      0.25              15.0     0
941         941  3.963363e+17      0.25               7.0     0
942         942  3.963364e+17      0.25              15.0     0

[943 rows x 5 columns]

## Concat

In [11]:
concat_df = pd.concat([train_df , score_df])
concat_df.head()

,Unnamed: 0,tweet_id,priority,postCategories_x,label,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,0,2.115660e+17,0.75,19.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2.116544e+17,0.50,15.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.116813e+17,0.25,15.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2.116856e+17,0.25,16.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2.118770e+17,0.25,7.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Create dummies

In [6]:
#pd.get_dummies

In [10]:
features_df = pd.get_dummies(data=concat_df, columns=['tweet_id','priority','priority','postCategories_x', 'label',
                                                'positive_sentiment', 'negative_sentiment',
                                                 'numb_of_questions', 'tweet_length', 'userFollowersCount', 'userFriendsCount', 
                                                 'user_list_count', 'dict_precision', 'dict_recall', 'dict_f_measure']
                                                 )

features_df

,tweet_id_2.115659744224256e+17,tweet_id_2.116544155039908e+17,tweet_id_2.1168130936865587e+17,tweet_id_2.116856211257426e+17,tweet_id_2.1187704914773606e+17,tweet_id_2.1188408299133338e+17,tweet_id_2.118930168924242e+17,tweet_id_2.1190481125009e+17,tweet_id_2.119103225823355e+17,tweet_id_2.1196419839623168e+17,...,dict_f_measure_1.3329999923706056e+16,dict_f_measure_1.4289999961853028e+16,dict_f_measure_1.5380000114440918e+16,dict_f_measure_1.6670000076293944e+16,dict_f_measure_2.1049999237060548e+16,dict_f_measure_2.2219999313354492e+16,dict_f_measure_2.3530000686645508e+16,dict_f_measure_2.6670000076293944e+16,dict_f_measure_3.1579999923706056e+16,dict_f_measure_3.5290000915527344e+16
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2944,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2945,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2946,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2947,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2948,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [14]:
# Split your data
train_df = features_df[concat_df['label'] == '0']
score_df = features_df[concat_df['label'] == '1']

# Drop your labels
#train_df = train_df.drop('label', axis=0)
#score_df = score_df.drop('label', axis=0)

In [15]:
#train_df.describe()
#score_df.describe()
train_df

,tweet_id_2.115659744224256e+17,tweet_id_2.116544155039908e+17,tweet_id_2.1168130936865587e+17,tweet_id_2.116856211257426e+17,tweet_id_2.1187704914773606e+17,tweet_id_2.1188408299133338e+17,tweet_id_2.118930168924242e+17,tweet_id_2.1190481125009e+17,tweet_id_2.119103225823355e+17,tweet_id_2.1196419839623168e+17,...,dict_f_measure_1.3329999923706056e+16,dict_f_measure_1.4289999961853028e+16,dict_f_measure_1.5380000114440918e+16,dict_f_measure_1.6670000076293944e+16,dict_f_measure_2.1049999237060548e+16,dict_f_measure_2.2219999313354492e+16,dict_f_measure_2.3530000686645508e+16,dict_f_measure_2.6670000076293944e+16,dict_f_measure_3.1579999923706056e+16,dict_f_measure_3.5290000915527344e+16
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
939,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
941,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
score_df

In [ ]:
score_df.to_csv(run + "score_df.csv", index=False)
score_df = pd.read_csv(run +"score_df.csv")

In [ ]:
train_df

In [ ]:
#temp
train_df = pd.read_csv(run +"train_df.csv")

In [ ]:
score_df.to_csv("score_df.csv", index=False)
train_df.to_csv("train_df.csv", index=False)

In [ ]:
# stackoverflow.com/questions/44026832/valueerror-number-of-features-of-the-model-must-match-the-input

In [ ]:
# Clean
train_df= clean_dataset_int(train_df)
train_df.head()

In [ ]:
# Clean
score_df= clean_dataset_int(score_df)
score_df.head()

In [ ]:
http://fastml.com/how-to-use-pd-dot-get-dummies-with-the-test-set/

def add_missing_dummy_columns( d, columns ):
    missing_cols = set( columns ) - set( d.columns )
    for c in missing_cols:
        d[c] = 0
        
def fix_columns( d, columns ):  

    add_missing_dummy_columns( d, columns )

    # make sure we have all the columns we need
    assert( set( columns ) - set( d.columns ) == set())

    extra_cols = set( d.columns ) - set( columns )
    if extra_cols:
        print "extra columns:", extra_cols

    d = d[ columns ]
    return d

def fix_columns_test():

    n_cols = 4
    n_rows = 5

    columns = [ "col_{}".format( x ) for x in range( n_cols )]

    # create the "new" set of columns
    new_columns = columns[:]            # copy
    new_columns.pop()
    new_columns.append( 'col_new' ) 

    # create the "new" dataframe
    n = np.random.random(( n_rows, n_cols ))
    d = pd.DataFrame( n, columns = new_columns )

    print d
    print "\n", columns

    fixed_d = fix_columns( d.copy(), columns )
    print "\n", fixed_d

    assert( list( fixed_d.columns ) == columns )