# Logical Regression

Logical Regression attempt to split the data

In [1]:
from datetime import datetime
import pandas as pd
import numpy as np


# Model
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC, SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import preprocessing
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

from xgboost import XGBClassifier
from sklearn.metrics import classification_report,confusion_matrix



from scipy import stats
import seaborn as sns

import matplotlib.pyplot as plt

import gzip
import glob
import json

import numpy as np
import pandas as pd
import seaborn as sns

import scipy.stats as ss

import matplotlib.pyplot as plt

from collections import Counter
%matplotlib inline
run_title = "baseline"

plt.rcParams['figure.figsize'] = (20.0, 10.0)
from mpl_toolkits.mplot3d import Axes3D

In [10]:
train = pd.read_csv("df_char.csv")
train.head()

,Unnamed: 0,tweet_id,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,0,1.155679e+18,20,630,190,1000,145000,13700,0,0,0,0
1,1,1.155712e+18,40,580,150,740,700,7030,10,0,0,0
2,2,1.155790e+18,70,500,430,2300,37260,10130,7990,0,0,0
3,3,1.155810e+18,20,630,180,990,679280,393110,13300,0,0,0
4,4,1.155847e+18,60,530,460,2370,18320,33710,190,0,0,0

In [14]:
# Reload the data to check everythings went alright
test = pd.read_csv("before_selection.csv")

# Timestamp will need to be reconfigured as index on each load
#test = test.set_index('timestamp')
test.head()

,Unnamed: 0,tweet_id,positive_sentiment,negative_sentiment,numb_of_questions,tweet_length,userFollowersCount,userFriendsCount,user_list_count,dict_precision,dict_recall,dict_f_measure
0,0,1.155485e+18,20,660,150,990,180,420,0,11109999656677246,11109999656677246,11109999656677246
1,1,1.155487e+18,10,390,520,2570,77090,28140,3920,0,0,0
2,2,1.155488e+18,20,630,170,980,5370,14860,200,0,0,0
3,3,1.155494e+18,40,570,630,2570,2950,21450,20,100,11109999656677246,10529999732971191
4,4,1.155495e+18,150,420,400,2170,16820,1040,510,0,0,0

In [5]:
## github.com/y3ksolver/LogicalRegression

In [6]:
X = test.drop("positive_sentiment", axis=1)
y = test["positive_sentiment"]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [15]:
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions)

In [9]:
confusion_matrix(y_test,predictions)

array([[  9,   0,   0, ...,   0,   0,   0],
       [ 98,   0,   0, ...,   0,   0,   0],
       [100,   0,   0, ...,   0,   0,   0],
       ...,
       [  1,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0]])